sudo: required
language: python
python:
  - "3.6"
os: 
  - linux
services:
  - docker
before_install:
  - docker build -t smarthome_gui .
install: "pip install tornado"
script:
  - docker run -i -t -d -p 8080:8080 smarthome_gui
  - sleep 5
  - curl localhost:8080
  - sleep 5
  - docker rm $(docker stop $(docker ps -a -q --filter ancestor=smarthome_gui --format="{{.ID}}"))
  - timeout 15s python ./ServerAPI.py &
  - sleep 5
  - curl localhost:3000

