sudo: required
language: python
os: 
  - linux
services:
  - docker
before_install:
  - docker build -t smarthome_gui .
script:
  - docker run -i -t -d -p 8080:8080 smarthome_gui
  - curl localhost:8080
  - docker rm $(docker stop $(docker ps -a -q --filter ancestor=smarthome_gui --format="{{.ID}}"))

